version: '3'

services:

  app_webserver:
    build: ./etc/nginx/
    container_name: app_webserver
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./../../rub:/var/www/rub
    links:
      - app_mysql
    networks:
      - app-network

  app_mysql:
    image: mysql:latest
    container_name: app_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: rub
    ports:
      - "3306:3306"
    volumes:
      - ./etc/mysql/conf.d:/etc/mysql/conf.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
